### ISSUE TITLE
Review package

### ISSUE THREAD

**Issue by margauxgo** [openwashdata/rwpfunctionality#2]
Hi @larnsce @mianzg could you please review this first package? Also, do I first add the badges after your review?

**Comment by larnsce** [comment]
Thank you, @margauxgo. Great job, especially considering that this is your first package! 

# README.rmd

You have a few references in the text. They need to be listed in a References section at the end. Did you copy/paste those from the original text of do you have a bibliography with these references (e.g. on Zotero)?

At the top of the README, we need to include a sentence like: This data was published alongside the article: "TITLE" by NAME et. al (YEAR), and then add citation in a section References at the end of the README. 

Thanks for including a few examples.

# DESCRIPTION

Have you reached out to the authors? They need to be listed as co-authors of this package. 

# data_processing.R

Looks great. You have implemented everything that we discussed.

# dictionary.csv

Looks complete with comprehensive descriptions. 

# Re: Badges

I will add those as part of the publishing process together with the DOI.

**Comment by margauxgo** [comment]
Thank you, @larnsce. I did copy/paste the references from the original text and reached out to the author but did not get a response yet.

**Comment by larnsce** [comment]
Okay, then I suggest you use Zotero to compile the references you have in a biblography. I have setup this collection for you:

https://www.zotero.org/groups/4445072/global_health_engineering/collections/XESCXRQW

Re: authors

Add them by name anyways. If we publish the package, then the names are already included and maybe they would be more willing to respond with an ORCID ID.

**Comment by margauxgo** [comment]
I made the changes accordingly.

However, I do not know why the citation appears that way (I appear as the only author, even tho I listed a few others). I tried to rewrite the CITATION.cff file but this did not help.

**Comment by mianzg** [comment]
- file https://github.com/openwashdata/rwpfunctionality/blob/main/R/rwpfunctionality.R in `R` seems not up-to-date
- readme
    - polish on readme with shorter display
    ```
    readr::read_csv("data-raw/dictionary.csv") |>
  dplyr::filter(file_name == "YOURDATA.rda") |>
  dplyr::select(variable_name:description) |> 
  knitr::kable() |> 
  kableExtra::kable_styling() |> 
  kableExtra::scroll_box(height = "400px")
    ```
    - not sure if pie chart is good idea, it often misleads the statistics with our visual bias
- GitHub keywords: provide a couple of keywords on the repo profile like the following:
<img width="342" alt="image" src="https://github.com/openwashdata/rwpfunctionality/assets/22420281/5a57d976-6a06-484d-8816-0aead5b41939">

**Comment by larnsce** [comment]
> However, I do not know why the citation appears that way (I appear as the only author, even tho I listed a few others). I tried to rewrite the CITATION.cff file but this did not help.

Thanks, I see the authors in `DESCRIPTION` now. You don't need to edit the `CITATION.cff`. It's created from  `DESCRIPTION` and I am currently doing that. It's a part of the workflow that is not well documented yet.

**Comment by larnsce** [comment]
> file https://github.com/openwashdata/rwpfunctionality/blob/main/R/rwpfunctionality.R in R seems not up-to-date

@mianzg: I am updating this file. I had @margauxgo only write the dictionary.csv for now.
